### ISSUE TITLE
Discuss and document file syncer workflow

### ISSUE THREAD

**Issue by surchs** [neurobagel/workflows#17]
We have a new workflow in this repo that takes files (workflows themselves) from a directory and then opens PRs against other repos in our org to add these files to their codebase: https://github.com/neurobagel/workflows/blob/515e86d88b05c1f9d5c52a34a6bf8b0a4d683afb/.github/workflows/sync_wf.yml (see also https://github.com/BetaHuhn/repo-file-sync-action)

The only reason (so far) for this workflow is to keep a central place for github workflows that all repos need, and then sync these workflows to the repos (including back to this repo).

However, this workflow was introduced without docs, issue or PR, so we should discuss and then document it.

Please give a general overview of how these work in the wiki

**Comment by surchs** [comment]
This needs more comments still to explain this.

**Comment by surchs** [comment]
For reviewer - I added a section here to explain our current GH workflows: https://github.com/neurobagel/documentation/wiki/How-we-work#automatic-github-processes

**Comment by alyssadai** [comment]
@surchs, the new wiki section reads very clearly, thanks again for all your effort on the workflows and for documenting things!

One curiosity/clarification question from me: not sure if I'm hallucinating something from back when I reviewed your various label workflows, but as of now, if a label that exists in the `planning` repo is renamed/edited in a _non_-`planning` repo, there is no workflow that is automatically triggered, right? That is, the label syncing is only responsive to label edits in `planning` (and it uses that repo as like the "ground truth" of the properties of the the shared labels?)

**Comment by surchs** [comment]
> if a label that exists in the planning repo is renamed/edited in a non-planning repo, there is no workflow that is automatically triggered

Yes, that's true. And I think we should make that more clear. Because it also means that you should

- create or edit common labels (i.e. labels you want in all repos) **only** in the planning repo
- only create **repo-specific labels** (i.e. labels that you don't want in any other repo) in the repo itself, because those won't be synced
