### ISSUE TITLE
Workflow failed when `_bot` label was added automatically

### ISSUE THREAD

**Issue by rmanaem** [neurobagel/workflows#24]
See [related job](https://github.com/neurobagel/annotation_tool/actions/runs/6017542915/job/16324514677).
Problem is:
- PR_automation gets triggered when bot opens PR and applies `_bot` label
- but then PR_automation workflow fails with "Bad credentials" on step 1
- when human user removes and reapplies `_bot` label, the PR_automation workflow triggers again and succeeds

So I think this is related to https://github.com/orgs/community/discussions/25565#discussioncomment-3429468 - which links to a place saying "GH workflows cannot trigger other workflows". The odd thing is that this would mean that the PR_automation workflow should not run at all. But it does run - and then fails with "Bad credentials".

However if I just force a bot to make a PR for me on click: https://github.com/neurobagel/workflows/actions/workflows/pr_test.yml and directly apply a label, then the PR_automation workflow does indeed **not** run :shrug: 

Additionally, the step it fails at needs and gets a PAT. So it is possible that the trigger works, but then the context is different for

**Comment by surchs** [comment]
I think the solution here is to change the way the workflow triggers from the label hook to a cron job. Every 12 hours should be enough for this to be useful, maybe even once a day. And then
- Look for all open pull requests
- Find the ones with the correct labels
- Check if they are on the project and add them if not
- Find the project card node id 
- Set status to community

**Comment by surchs** [comment]
We'll have to use workflow nesting here: https://docs.github.com/en/actions/using-workflows/reusing-workflows#nesting-reusable-workflows so we can have two job matrices

- level 1: find all repos
- level 2: find all PRs within the repo

as long as the complete set of jobs stays below 256 jobs this will work

**Comment by surchs** [comment]
One thing that just occurred to me: the proposed workflow replaces all these little workflows we have already pushed to every repo. So we still have to remove all of those (and also remove the template workflow from the workflows repo).
