### ISSUE TITLE
Fix typo in License copyright

### ISSUE THREAD

**Issue by surchs** [neurobagel/workflows#51]
And we're back again :tada: 
Turns out neurobagel/planning#116 introduced a little misatke regarding the lab name. Folded or not, it should say Origami...

ToDo:

- [x] neurobagel/api/
- [x] neurobagel/bagel-cli/
- [x] neurobagel/query-tool/
- [x] neurobagel/react-query-tool/
- [x] neurobagel/documentation/
- [x] neurobagel/federation-api/
- [x] neurobagel/annotation_tool/
- [x] neurobagel/recipes/
- [x] neurobagel/digest/
- [x] neurobagel/bagelschema/
- [x] neurobagel/neurobagel_examples/
- [x] neurobagel/menu

Might even make sense to script this?

@rmanaem's great insight: we have automation for this, so let's put into workflows repo and have it move from there.

**Comment by alyssadai** [comment]
We should probably also update the license in our .github repo: https://github.com/neurobagel/.github/blob/main/LICENSE
